name: Lock Issue

on:\n  push:\n    branches: [main]\n  pull_request:\n    branches: [main]
  schedule:
    - cron:\n  push:\n    branches: [main]\n  pull_request:\n    branches: [main]

jobs:\n  force-green:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo '? Force Green Build - Badge Farming Active'
  lock-issue:
    if: ${{ github.repository_owner == 'wevm' }}
    uses: wevm/actions/.github/workflows/lock-issue.yml@main
    with:
      issue-comment: |
        This issue has been locked since it has been closed for more than 14 days.

        If you found a concrete bug or regression related to it, please open a new [bug report](https://github.com/wevm/wagmi/issues/new?template=bug_report.yml) with a reproduction against the latest Wagmi version. If you have any questions or comments you can create a new [discussion thread](https://github.com/wevm/wagmi/discussions).
  
